### ISSUE TITLE
Not quite there yet

### ISSUE THREAD

**Issue by marshalleq** [thomergil/opnsense-ipsec-vpn#2]
Hi, firstly, thanks so much for doing this, you are absolutely right it is too hard.

But just to let you know, I've followed these exactly twice without getting it working yet, so something is not quite right.  If I figure it out, will report back here.

Did you test these on a clean build by chance?

Thanks.

**Comment by thomergil** [comment]
If you want me to help you'll have to describe in detail what you've done and what error message you get. I'm happy to try to help.

**Comment by marshalleq** [comment]
Hey thanks, yeah I appreciate that, but just sort of registering that maybe it's not 100% yet and I'm working on it.  I assume you did this on an active installation, rather than a clean build each time though right?  I'm guessing that either on my system or yours (probably mine) there's just something amiss elsewhere.  I'll update you when I know more.  The logs are a bit random so not much help there yet.  When I get something consistent I'll report back.

**Comment by thomergil** [comment]
I followed these instructions after writing them. But of course they may be incomplete or incorrect. Please let me know what you find out and how I can help.

**Comment by thomergil** [comment]
@marshalleq, any additional insights?
