### ISSUE TITLE
Multiple ipsec clients behind same NAT device with single public IP to one OPNSense VPN server

### ISSUE THREAD

**Issue by surzn** [thomergil/opnsense-ipsec-vpn#6]
**Thanks for sharing!**

Though I encountered one issue:

Let's say that we have 2 employees with their notebooks in a remote office, connected to office LAN with a simple internet connection that has single public IP. The two use their vpn connections as they would do everywhere, but in this case they come out natted behind the same public IP. Always who comes first who can make successful VPN connection, 2nd person will face server no response.

This is understandable due to fixed NAT ports for 500/4500, but how to overcome?

Some other IPSEC solutions can tell the difference of connections from different usernames and process their connections accordingly, even they come in form same public IP address. 

I failed to find the same the right way to do it in OPNSense for IPSEC.

I don't want to move to SSL based OpenVPN yet. 8-).

**Comment by thomergil** [comment]
This is beyond the scope of the instructions I provided. But when I asked an LLM (Claude.ai), it said the following. **I cannot confirm these instructions, nor do I attest they're even remotely accurate or sensible.**

```
This is a known limitation with IKE/IPsec when multiple clients are behind NAT using the same IP. Here are two solutions:

1. Enable NAT-T traversal with IKEv2 Mobility and Multihoming Protocol (MOBIKE):
- In OPNsense IPsec settings, enable "Enable NAT Traversal" and "Enable MOBIKE support"
- Configure unique client IDs for each user
- Set Phase 1 proposal to IKEv2

2. Use port forwarding on the remote office router:
- Forward UDP 500 and 4500 to different internal IPs for each client
- Configure static NAT mappings for VPN traffic

The first option is preferred as it's more scalable and doesn't require router configuration.

[...]
```

**Comment by surzn** [comment]
Appreciate the quick response!

I actually tried multiple ways, including different GPTs, no valid solution so far.

We are using IKEv1 instead of IKEv2 here, and 2nd option doesn't work for more than 2 users, not sure even it would work too.

Anyway, just tried to check your opinion quickly since you posted such sophisticated instruction for IKEv1 IPSec VPN. 

Maybe migrating to IKEv2 can help... 

Though I didn't make it work even for single user per below guide
https://docs.opnsense.org/manual/how-tos/ipsec-swanctl-rw-ikev2-eap-mschapv2.html
Cert installation to client is another challenge that makes me reluctant to go there.
